"""update chatbot model ENUM

Revision ID: 2d6b1114f71c
Revises: b788b9964825
Create Date: 2025-12-18 12:27:38.959554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d6b1114f71c'
down_revision: Union[str, Sequence[str], None] = 'b788b9964825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the new enum type
    botstatus = postgresql.ENUM('ACTIVE', 'ARCHIVED', 'PENDING', 'FAILED', name='botstatus')
    botstatus.create(op.get_bind(), checkfirst=True)

    # 2. Alter the column with USING
    op.execute(
        """
        ALTER TABLE chatbots 
        ALTER COLUMN status 
        TYPE botstatus 
        USING status::text::botstatus
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    filestatus = postgresql.ENUM('ACTIVE', 'ARCHIVED', name='filestatus')
    op.alter_column(
        'chatbots',
        'status',
        existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'PENDING', 'FAILED', name='botstatus'),
        type_=filestatus,
        existing_nullable=False
    )
    
    botstatus = postgresql.ENUM('ACTIVE', 'ARCHIVED', 'PENDING', 'FAILED', name='botstatus')
    botstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
