"""update chatbots table

Revision ID: 9783e54fee98
Revises: 2914b80237b9
Create Date: 2025-12-13 17:51:47.239241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9783e54fee98'
down_revision: Union[str, Sequence[str], None] = '2914b80237b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('name', sa.String(), nullable=False))
    op.add_column('chatbots', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'description')
    op.drop_column('chatbots', 'name')
    # ### end Alembic commands ###
