"""add allowed hosts for chatbots

Revision ID: d60a30781572
Revises: c1d247647aab
Create Date: 2025-12-25 12:06:54.643288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd60a30781572'
down_revision: Union[str, Sequence[str], None] = 'c1d247647aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('allowed_hosts', postgresql.JSONB(astext_type=sa.Text()), server_default='["*"]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'allowed_hosts')
    # ### end Alembic commands ###
